### PR TITLE
ACL duplicate button

### PR DESCRIPTION
**Pull request by belljohan3**

### CODE REVIEW

**Comment by ivanslabbert** [comment]
Visual check: Functions as required.
Button placement: not horizontally centre in div (visible when hovering). Overall it needs to move a bit more right (same distance from right border as from top)? (It feels a bit off where it is now)

image

**Comment by ivanslabbert** [comment]
@laurensgroeneveld comments?

**Review by ivanslabbert — APPROVED** [review]
Thanks Johan!

**Comment by laurensgroeneveld** [comment]
> Visual check: Functions as required.
> Button placement: not horizontally centre in div (visible when hovering). Overall it needs to move a bit more right (same distance from right border as from top)? (It feels a bit off where it is now) - Edit: Might be fixed using the new "muted" button state as per https://github.com/bccsa/luminary/pull/144.

Just to come back to this: This is because there is currently an empty slot passed like this `<LButton [props]></LButton>`. It will be fixed by making the tag selfclosing, like `<LButton [props] />`

**Pull request merged**
